{{- if .Values.edgeProxy.disableAttachments }}
{{- $edgeSvc := include "ticketingZammad.edgeProxyService" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $edgeSvc }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: zammad-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: zammad-edge
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: zammad-edge
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/edge-proxy-configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nginx
          image: {{ .Values.edgeProxy.image | quote }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: {{ $edgeSvc }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $edgeSvc }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: zammad-edge
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: zammad-edge
  ports:
    - name: http
      port: 8080
      targetPort: http
{{- end }}
